---
- name: ansibleprac
  hosts: all

  roles:
    - ansr
  
  
    
  #vars_files:
     #- vars/ansible.yml
  # become: yes
  # gather_facts: false
  # tasks:
   


    # - name: Install nginx
    #   apt:
    #     name: nginx
    #     state: present
    #   notify: start nginx
        
    
     
  #    - name: copying
  #     copy:
  #        src: html/
  #        dest: /var/www/html/
  #     force: yes
    
  # handlers:
  #    - name: start nginx
  #      service:
  #          name: nginx
  #          state: started
     


    # - name: changing mode of index.html file
    #   file:
    #     path: /var/www/html/index.html
    #     owner: root
    #     group: root
    #     mode: '0775'
     


    # - name: delete default nginx file
    #   file:
    #     path: /etc/nginx/sites-enabled/default
    #     state: absent
    #   notify: restart nginx

    # - name: copy default nginx site
    #   template:
    #      src: nginx.conf.j2
    #      dest: /etc/nginx/sites-enabled/{{ domain }}
    #      owner: root
    #      group: root
    #   notify: restart nginx

    # - name: allow all access to tcp port 80
    #   ufw:
    #     rule: allow
    #     port: '80'
    #     proto: tcp

      
           
           
           
      

    